version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    env_file:
      - .env
    ports:
      - "${JENKINS_UI_PORT}:8080"     # Acesso à UI do Jenkins
      - "${JENKINS_AGENT_PORT}:50000"   # Comunicação com agentes Jenkins (opcional)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # Permite Jenkins rodar Docker no host
    restart: unless-stopped

volumes:
  jenkins_home:
