version: '3.9'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    env_file:
      - .env
    user: root   # garante que Jenkins tenha permissão no docker.sock
    ports:
      - "${JENKINS_UI_PORT}:8080"        # UI do Jenkins
      - "${JENKINS_AGENT_PORT}:50000"    # Comunicação com agentes Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Jenkins usa Docker do host
    restart: unless-stopped

volumes:
  jenkins_home:
